# Generated by Django 5.0.6 on 2026-07-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='US/Eastern', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_in', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_runs', to='noon.account')),
            ],
            options={
                'db_table': 'ingest_runs',
            },
        ),
        migrations.CreateModel(
            name='ConversionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('conversion_id', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('offer_id', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=2)),
                ('tracking_token', models.CharField(blank=True, max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(max_length=16)),
                ('raw', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_rows', to='noon.account')),
                ('ingest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_rows', to='noon.ingestrun')),
            ],
            options={
                'db_table': 'conversion_rows',
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('stages', models.JSONField(default=dict)),
                ('exceptions_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='noon.account')),
            ],
            options={
                'db_table': 'pipeline_runs',
            },
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingest_runs', to='noon.pipelinerun'),
        ),
        migrations.CreateModel(
            name='ProfitFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('platform', models.CharField(max_length=16)),
                ('campaign_id', models.CharField(max_length=255)),
                ('ad_id', models.CharField(blank=True, max_length=255)),
                ('offer_id', models.CharField(blank=True, max_length=255)),
                ('geo', models.CharField(max_length=2)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reconciled_conversions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reconciled_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_reported_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('revenue_status', models.CharField(max_length=16)),
                ('ruleset_version', models.CharField(max_length=32)),
                ('source_keys', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('grain_key', models.CharField(max_length=255, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_facts', to='noon.account')),
            ],
            options={
                'db_table': 'profit_facts',
            },
        ),
        migrations.CreateModel(
            name='SpendRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('campaign_id', models.CharField(max_length=255)),
                ('campaign_name', models.CharField(max_length=255)),
                ('ad_id', models.CharField(blank=True, max_length=255)),
                ('ad_name', models.CharField(blank=True, max_length=255)),
                ('offer_id', models.CharField(blank=True, max_length=255)),
                ('geo', models.CharField(max_length=2)),
                ('tracking_token', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=14)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('platform_reported_conversions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_reported_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('ingest_key', models.CharField(max_length=255, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_rows', to='noon.account')),
                ('ingest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_rows', to='noon.ingestrun')),
            ],
            options={
                'db_table': 'spend_rows',
            },
        ),
    ]
