# Generated by Django 5.0.6 on 2026-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitfact',
            name='attribution',
            field=models.CharField(default='token', max_length=16),
        ),
    ]
